// ============================================================
// Test script for markdown generator — no external services needed
// Tests the markdown building functions with mock data
// ============================================================

import type {
  ScreenAnalysis,
  MarkdownJourneyContent,
} from "@docuagent/shared";

// ---------------------------------------------------------------------------
// Inline the pure markdown builders from markdown-generator.ts for testing
// (avoids needing Supabase/Claude connections)
// ---------------------------------------------------------------------------

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 60);
}

function buildJourneyMarkdown(
  content: MarkdownJourneyContent,
  screenshotFilenames: Map<string, string>,
): string {
  const lines: string[] = [];

  lines.push(`# ${content.title}`);
  lines.push("");
  lines.push(content.intro);
  lines.push("");

  const heroFilename = screenshotFilenames.get(content.hero_screenshot_ref);
  if (heroFilename) {
    lines.push(`![${content.title}](./images/${heroFilename})`);
    lines.push("");
  }

  lines.push("## How to get there");
  lines.push("");
  lines.push(content.how_to_get_there);
  lines.push("");

  lines.push("## Steps");
  lines.push("");
  for (let i = 0; i < content.steps.length; i++) {
    const step = content.steps[i];
    lines.push(`${i + 1}. ${step.action}`);
    if (step.detail) {
      lines.push(`   ${step.detail}`);
    }
    const stepRef = content.step_screenshot_refs[i];
    if (stepRef) {
      const filename = screenshotFilenames.get(stepRef);
      if (filename && stepRef !== content.hero_screenshot_ref) {
        lines.push("");
        lines.push(`   ![Step ${i + 1}](./images/${filename})`);
      }
    }
  }
  lines.push("");

  if (content.permission_notes.length > 0) {
    for (const note of content.permission_notes) {
      lines.push(`> **Note:** ${note}`);
      lines.push("");
    }
  }

  if (content.fields.length > 0) {
    lines.push("## Fields");
    lines.push("");
    lines.push("| Field | Type | Required | Description |");
    lines.push("|-------|------|----------|-------------|");
    for (const field of content.fields) {
      const req = field.required ? "Yes" : "No";
      const desc = field.description.replace(/\|/g, "\\|");
      lines.push(`| ${field.label} | ${field.type} | ${req} | ${desc} |`);
    }
    lines.push("");
  }

  if (content.tips.length > 0) {
    lines.push("## Tips");
    lines.push("");
    for (const tip of content.tips) {
      lines.push(`- ${tip}`);
    }
    lines.push("");
  }

  if (content.related.length > 0) {
    lines.push("## Related");
    lines.push("");
    for (const rel of content.related) {
      lines.push(`- [${rel.title}](./${rel.slug}.md)`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function buildIndexMarkdown(
  appName: string,
  overview: string,
  journeys: { title: string; slug: string }[],
  hasGlossary: boolean,
): string {
  const lines: string[] = [];

  lines.push(`# ${appName} Documentation`);
  lines.push("");
  lines.push(overview);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Contents");
  lines.push("");
  lines.push("- [Quick Start](./quick-start.md)");
  lines.push("- [Navigation](./navigation.md)");
  lines.push("");
  lines.push("### Guides");
  lines.push("");
  for (const j of journeys) {
    lines.push(`- [${j.title}](./${j.slug}.md)`);
  }
  lines.push("");
  if (hasGlossary) {
    lines.push("### Reference");
    lines.push("");
    lines.push("- [Glossary](./glossary.md)");
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push(`*Generated by DocuAgent on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}*`);
  lines.push("");

  return lines.join("\n");
}

function buildQuickStartMarkdown(appName: string, steps: string[]): string {
  const lines: string[] = [];
  lines.push(`# Quick Start`);
  lines.push("");
  lines.push(`Get up and running with **${appName}** in five steps.`);
  lines.push("");
  for (let i = 0; i < steps.length; i++) {
    lines.push(`${i + 1}. ${steps[i]}`);
  }
  lines.push("");
  return lines.join("\n");
}

function buildNavigationMarkdown(description: string): string {
  const lines: string[] = [];
  lines.push("# Navigation");
  lines.push("");
  lines.push(description);
  lines.push("");
  return lines.join("\n");
}

function buildGlossaryMarkdown(
  glossary: { term: string; definition: string }[],
): string {
  const lines: string[] = [];
  lines.push("# Glossary");
  lines.push("");
  const sorted = [...glossary].sort((a, b) => a.term.localeCompare(b.term));
  for (const entry of sorted) {
    lines.push(`**${entry.term}**`);
    lines.push(`${entry.definition}`);
    lines.push("");
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Test with mock data
// ---------------------------------------------------------------------------

console.log("=== DocuAgent Markdown Generator Test ===\n");

// Mock journey content (simulating what Claude would return)
const mockJourney: MarkdownJourneyContent = {
  title: "Create a New Project",
  slug: "create-a-new-project",
  intro: "Projects are the foundation of Acme SaaS. Create one to start organizing your team's work and tracking progress toward goals.",
  how_to_get_there: "From the sidebar, click **Projects**, then click **New Project**.",
  steps: [
    { action: "Click **New Project** in the top-right corner.", detail: "A creation form appears." },
    { action: "Enter a project name in the **Project Name** field.", detail: "Use a descriptive name like \"Q1 Marketing Campaign\"." },
    { action: "Select a team from the **Team** dropdown." },
    { action: "Set the **Start Date** and **End Date**." },
    { action: "Click **Create Project**." },
  ],
  permission_notes: [
    "Only **Owner** and **Admin** role users can create projects.",
  ],
  fields: [
    { label: "Project Name", type: "text", required: true, description: "The display name for the project. Max 100 characters." },
    { label: "Team", type: "dropdown", required: true, description: "The team that owns this project." },
    { label: "Start Date", type: "date", required: false, description: "When the project begins. Defaults to today." },
    { label: "End Date", type: "date", required: false, description: "Target completion date." },
    { label: "Description", type: "textarea", required: false, description: "Optional project description. Supports markdown formatting." },
  ],
  tips: [
    "Use clear, descriptive project names so team members can find them easily.",
    "Set realistic end dates to help track progress.",
    "Add a description to give team members context about the project goals.",
  ],
  related: [
    { title: "Manage Team Members", slug: "manage-team-members" },
    { title: "Configure Project Settings", slug: "configure-project-settings" },
  ],
  hero_screenshot_ref: "screen_0",
  step_screenshot_refs: ["screen_0", "screen_1", "screen_2", "screen_3", "screen_4"],
};

const mockJourney2: MarkdownJourneyContent = {
  title: "Manage Team Members",
  slug: "manage-team-members",
  intro: "Invite colleagues to your workspace and assign roles to control access. Team management is essential for collaboration.",
  how_to_get_there: "From the sidebar, click **Settings**, then select the **Team** tab.",
  steps: [
    { action: "Click **Invite Member**." },
    { action: "Enter the member's **Email** address." },
    { action: "Select a **Role** (Member or Admin)." },
    { action: "Click **Send Invite**." },
  ],
  permission_notes: [
    "Only **Owner** role users can invite team members.",
  ],
  fields: [
    { label: "Email", type: "email", required: true, description: "Team member's email. Must be a valid email format." },
    { label: "Role", type: "radio", required: false, description: "Member (default) or Admin. Only Admins can manage billing and settings." },
  ],
  tips: [
    "Invited members receive an email with a link to join your workspace.",
    "You can change a member's role at any time from the team settings.",
  ],
  related: [
    { title: "Create a New Project", slug: "create-a-new-project" },
  ],
  hero_screenshot_ref: "screen_5",
  step_screenshot_refs: ["screen_5", "screen_6", "screen_7", "screen_8"],
};

// Mock screenshot filenames
const screenshotFilenames = new Map<string, string>();
for (let i = 0; i < 10; i++) {
  screenshotFilenames.set(`screen_${i}`, `screen_${i}.png`);
}

// Build all markdown files
const journeyMd1 = buildJourneyMarkdown(mockJourney, screenshotFilenames);
const journeyMd2 = buildJourneyMarkdown(mockJourney2, screenshotFilenames);

const indexMd = buildIndexMarkdown(
  "Acme SaaS",
  "Acme SaaS is a project management platform that helps teams organize work, track progress, and collaborate effectively. Built for small to mid-sized teams, it provides intuitive tools for project planning, task management, and team coordination.",
  [
    { title: "Create a New Project", slug: "create-a-new-project" },
    { title: "Manage Team Members", slug: "manage-team-members" },
  ],
  true,
);

const quickStartMd = buildQuickStartMarkdown("Acme SaaS", [
  "Log in to **Acme SaaS** at your workspace URL.",
  "Click **Projects** in the sidebar to view existing projects.",
  "Click **New Project** to create your first project.",
  "Navigate to **Settings** > **Team** to invite team members.",
  "Explore the **Dashboard** for an overview of activity and metrics.",
]);

const navMd = buildNavigationMarkdown(
  "Acme SaaS uses a left sidebar for primary navigation. The sidebar contains links to Dashboard, Projects, Team, and Settings. The top bar displays your workspace name, notifications, and profile menu. The main content area shows the selected section.",
);

const glossaryMd = buildGlossaryMarkdown([
  { term: "Workspace", definition: "The top-level container for all your projects, team members, and settings." },
  { term: "Project", definition: "A collection of tasks and milestones organized toward a common goal." },
  { term: "Member", definition: "A user with standard access who can view and edit projects." },
  { term: "Admin", definition: "A user with elevated permissions who can manage team settings and billing." },
  { term: "Owner", definition: "The workspace creator with full administrative access." },
]);

// Print results
console.log("=== index.md ===\n");
console.log(indexMd);

console.log("\n=== quick-start.md ===\n");
console.log(quickStartMd);

console.log("\n=== navigation.md ===\n");
console.log(navMd);

console.log("\n=== create-a-new-project.md ===\n");
console.log(journeyMd1);

console.log("\n=== manage-team-members.md ===\n");
console.log(journeyMd2);

console.log("\n=== glossary.md ===\n");
console.log(glossaryMd);

// Validate output
console.log("\n=== VALIDATION ===\n");

const bannedPhrases = ["This page displays", "You'll see", "Here you can", "This is designed to", "As shown above"];
const allContent = [journeyMd1, journeyMd2, indexMd, quickStartMd, navMd, glossaryMd].join("\n");

let valid = true;

for (const phrase of bannedPhrases) {
  if (allContent.includes(phrase)) {
    console.error(`FAIL: Found banned phrase "${phrase}"`);
    valid = false;
  }
}

// Check field tables exist
if (!journeyMd1.includes("| Field | Type | Required | Description |")) {
  console.error("FAIL: Journey 1 missing field table");
  valid = false;
}

if (!journeyMd2.includes("| Field | Type | Required | Description |")) {
  console.error("FAIL: Journey 2 missing field table");
  valid = false;
}

// Check permission notes
if (!journeyMd1.includes("> **Note:**")) {
  console.error("FAIL: Journey 1 missing permission note");
  valid = false;
}

// Check screenshots
if (!journeyMd1.includes("![Create a New Project](./images/screen_0.png)")) {
  console.error("FAIL: Journey 1 missing hero screenshot");
  valid = false;
}

// Check steps are numbered
if (!journeyMd1.includes("1. Click **New Project**")) {
  console.error("FAIL: Journey 1 steps not properly numbered/formatted");
  valid = false;
}

// Check bold UI elements
if (!journeyMd1.includes("**Project Name**")) {
  console.error("FAIL: Journey 1 missing bold field names");
  valid = false;
}

// Check index links
if (!indexMd.includes("[Quick Start](./quick-start.md)")) {
  console.error("FAIL: Index missing quick start link");
  valid = false;
}
if (!indexMd.includes("[Create a New Project](./create-a-new-project.md)")) {
  console.error("FAIL: Index missing journey link");
  valid = false;
}
if (!indexMd.includes("[Glossary](./glossary.md)")) {
  console.error("FAIL: Index missing glossary link");
  valid = false;
}

// Check glossary is alphabetically sorted
if (!glossaryMd.includes("**Admin**\n") || glossaryMd.indexOf("**Admin**") > glossaryMd.indexOf("**Owner**")) {
  console.error("FAIL: Glossary not alphabetically sorted");
  valid = false;
}

// Check code analysis enrichment in field table
if (!journeyMd1.includes("Max 100 characters")) {
  console.error("FAIL: Field table missing validation rules (code analysis enrichment)");
  valid = false;
}

// Check related links
if (!journeyMd1.includes("[Manage Team Members](./manage-team-members.md)")) {
  console.error("FAIL: Journey 1 missing related links");
  valid = false;
}

if (valid) {
  console.log("ALL CHECKS PASSED!");
} else {
  console.error("\nSome checks failed.");
  process.exit(1);
}

// File count
const files = ["index.md", "quick-start.md", "navigation.md", "create-a-new-project.md", "manage-team-members.md", "glossary.md"];
console.log(`\nFiles generated: ${files.length}`);
for (const f of files) {
  console.log(`  ${f}`);
}

// Content sizes
console.log(`\nContent sizes:`);
console.log(`  index.md: ${Buffer.from(indexMd).length} bytes`);
console.log(`  quick-start.md: ${Buffer.from(quickStartMd).length} bytes`);
console.log(`  navigation.md: ${Buffer.from(navMd).length} bytes`);
console.log(`  create-a-new-project.md: ${Buffer.from(journeyMd1).length} bytes`);
console.log(`  manage-team-members.md: ${Buffer.from(journeyMd2).length} bytes`);
console.log(`  glossary.md: ${Buffer.from(glossaryMd).length} bytes`);
